### ISSUE TITLE
[BUG] integer / Rational does not produce the correct result

### ISSUE THREAD

**Issue by msrd0** [ijagberg/rational#10]
When I have a rational with value 6 and an integer with value 1, then `1 / 6` produces result `6 / 1`. I looked at the implementation and it looks like you are using the left-hand and right-hand side of a _division_ interchangably: https://docs.rs/rational/latest/src/rational/ops.rs.html#233-239

**Comment by ijagberg** [comment]
Nice catch, I will fix this asap and add more unit tests for math ops.

**Comment by ijagberg** [comment]
#2b5d305e3b107a2c123fb293276980ee6c93afd7 fixes this bug for the Sub, Div, and Rem operators, will publish a new version to crates.io later today.

**Comment by msrd0** [comment]
Thanks for the fix

**Comment by ijagberg** [comment]
Version 1.2.1 is now on crates.io.
