### ISSUE TITLE
Please implement `std::iter::Product`

### ISSUE THREAD

**Issue by msrd0** [ijagberg/rational#6]
Please implement [`Product`](https://doc.rust-lang.org/stable/std/iter/trait.Product.html). This allows to call `.product()` over an iterator of `Rational`s.

**Comment by ijagberg** [comment]
I have created a PR for this, and I implemented the `Sum` trait as well. Thanks for the suggestion! Will release a new version later today when I have a little more time to review some other changes that will go out.

**Comment by msrd0** [comment]
Oh wow that was fast. Thank you very much.

**Comment by ijagberg** [comment]
No problem :) I have released version 1.1.0 now which should fix your issue. Please let me know if it works!
