### ISSUE TITLE
Please implement `is_zero` and `is_positive`

### ISSUE THREAD

**Issue by msrd0** [ijagberg/rational#9]
Thanks for this library! It would be nice if we had `is_zero` and `is_positive` in addition to `is_negative`.

**Comment by ijagberg** [comment]
Thanks for the suggestion. I think `is_positive` and `is_negative` are useful and feature-symmetric with the `i8`, `i16`... primitives of Rust, which all have similar methods. But for that reason I don't think `is_zero` is necessary, and would suggest simply comparing a `Rational` with zero instead. Pushing an update later today.

**Comment by msrd0** [comment]
I was just suggesting `is_zero` as its a little bit more verbose to write `== Rational::zero()` than it is to write `== 0`. Maybe you could instead allow comparisons with integer types?

**Comment by ijagberg** [comment]
Ah, that's a good idea. Honestly thought that was already implemented :) 

I just pushed a commit to the develop branch with these additions, you can check it out if you want, I'll publish a new version of the crate in the coming days.

**Comment by ijagberg** [comment]
Have published version 1.2.0 now with these changes.
